_target_: bcp.onlinelearning.ExcInhAssemblyOnlineLearningVF
data_dim: 20
nb_ensembles: 20
nb_exc: 240
nb_inh: 60
nb_outputs: 2
actE:
  _target_: bcp.core.activation.ReLU
actI:
  _target_: bcp.core.activation.ReLU
tauE: 30e-3
tauI: 20e-3
tauOut: 30e-3
tauPre: 30e-3
tauSlow: 10.0
eta_OUT: 0.2
eta_FF: 0.2
alpha: 0.5
use_bias: True
perc_overlap: ${perc_random_memb}
binary_membership: False
normalize_membership: True
global_fb: False
random_fb_per_ensemble: False
random_fb_per_neuron: False
only_disinhibitory_feedback: False
controller:
  _target_: bcp.core.LeakyPIController
  dim_output: 2
  loss: 
    _target_: bcp.core.losses.MSE
    name: 'MSE'
  k_p: 5
  k_i: 0.0
  leak: 1.0
  tau: 100e-3
clip_hidden_weights: True
clip_val: 1.0
weight_decay: 0.0